language: node_js
sudo: false
node_js:
  - '0.12'
  - '0.11'
  - '0.10'

cache:
  directories:
    - node_modules
    - bower_components
    - docs/bower_components

branches:
  only:
    - master
    - stage
    - test
    - dev
