language: node_js
sudo: false
node_js:
  - '0.12'
  - '0.11'
  - '0.10'

env:
  global:
    - CODACY_PROJECT_TOKEN=f93abfb3437b45da8124952e2d71c564

cache:
  directories:
    - node_modules
    - bower_components
    - docs/bower_components

branches:
  only:
    - master
    - stage
    - test
    - dev

after_success:
  - npm run codacy
  - npm run coveralls
